### ISSUE TITLE
How to load profiles in HttpContext.EnableOutputCaching(<profile name>);

### ISSUE THREAD

**Issue by hermesramos** [madskristensen/WebEssentials.AspNetCore.OutputCaching#10]
Howdy,

Is it possible to load a profile from its name. Example: HttpContext.EnableOutputCaching(<profile name>);

Thanks in advance

**Comment by slangeder** [comment]
You can inject an instance of the `OutputCacheOptions` class and access the registered profiles using the Profiles Dictionary.

```
public class MyClass : Controller
{
    private readonly OutputCacheOptions _options;

    public MyClass(OutputCacheOptions options)
    {
        this._options = options;
    }

    public IActionResult Get()
    {
        HttpContext.EnableOutputCaching(_options.Profiles["ProfileName"]);
        return Ok();
    }
}
```

**Comment by hermesramos** [comment]
THANK YOU!

![image](https://user-images.githubusercontent.com/11175800/62258489-0d14ef00-b3e1-11e9-8415-0df5f0d2e9ea.png)
