### ISSUE TITLE
Remove nuget key

### ISSUE THREAD

**Issue by tiagosalgado** [madskristensen/WebEssentials.AspNetCore.OutputCaching#3]
Hi, @madskristensen  just a warning as your appveyor.yml file has your nuget apikey included. Cheers

**Comment by madskristensen** [comment]
Thanks, but that is an encrypted representation of the API key and not the key itself. You need my appveyor login to be able to use it :)

**Comment by tiagosalgado** [comment]
That makes more sense now 👍 Anyway, worth to let you know.
